// Code generated by protoc-gen-go. DO NOT EDIT.
// source: SftpPb/sftp.proto

package sftppb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Sftp struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	PassWord             string   `protobuf:"bytes,2,opt,name=passWord,proto3" json:"passWord,omitempty"`
	SystemId             string   `protobuf:"bytes,3,opt,name=systemId,proto3" json:"systemId,omitempty"`
	HostKey              string   `protobuf:"bytes,4,opt,name=hostKey,proto3" json:"hostKey,omitempty"`
	FileName             string   `protobuf:"bytes,5,opt,name=fileName,proto3" json:"fileName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Sftp) Reset()         { *m = Sftp{} }
func (m *Sftp) String() string { return proto.CompactTextString(m) }
func (*Sftp) ProtoMessage()    {}
func (*Sftp) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b70380debb315ef, []int{0}
}

func (m *Sftp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Sftp.Unmarshal(m, b)
}
func (m *Sftp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Sftp.Marshal(b, m, deterministic)
}
func (m *Sftp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Sftp.Merge(m, src)
}
func (m *Sftp) XXX_Size() int {
	return xxx_messageInfo_Sftp.Size(m)
}
func (m *Sftp) XXX_DiscardUnknown() {
	xxx_messageInfo_Sftp.DiscardUnknown(m)
}

var xxx_messageInfo_Sftp proto.InternalMessageInfo

func (m *Sftp) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *Sftp) GetPassWord() string {
	if m != nil {
		return m.PassWord
	}
	return ""
}

func (m *Sftp) GetSystemId() string {
	if m != nil {
		return m.SystemId
	}
	return ""
}

func (m *Sftp) GetHostKey() string {
	if m != nil {
		return m.HostKey
	}
	return ""
}

func (m *Sftp) GetFileName() string {
	if m != nil {
		return m.FileName
	}
	return ""
}

type CopyLocalToRemoteRequest struct {
	Sftp                 *Sftp    `protobuf:"bytes,1,opt,name=sftp,proto3" json:"sftp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CopyLocalToRemoteRequest) Reset()         { *m = CopyLocalToRemoteRequest{} }
func (m *CopyLocalToRemoteRequest) String() string { return proto.CompactTextString(m) }
func (*CopyLocalToRemoteRequest) ProtoMessage()    {}
func (*CopyLocalToRemoteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b70380debb315ef, []int{1}
}

func (m *CopyLocalToRemoteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CopyLocalToRemoteRequest.Unmarshal(m, b)
}
func (m *CopyLocalToRemoteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CopyLocalToRemoteRequest.Marshal(b, m, deterministic)
}
func (m *CopyLocalToRemoteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CopyLocalToRemoteRequest.Merge(m, src)
}
func (m *CopyLocalToRemoteRequest) XXX_Size() int {
	return xxx_messageInfo_CopyLocalToRemoteRequest.Size(m)
}
func (m *CopyLocalToRemoteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CopyLocalToRemoteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CopyLocalToRemoteRequest proto.InternalMessageInfo

func (m *CopyLocalToRemoteRequest) GetSftp() *Sftp {
	if m != nil {
		return m.Sftp
	}
	return nil
}

type CopyLocalToRemoteResponse struct {
	Result               string   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CopyLocalToRemoteResponse) Reset()         { *m = CopyLocalToRemoteResponse{} }
func (m *CopyLocalToRemoteResponse) String() string { return proto.CompactTextString(m) }
func (*CopyLocalToRemoteResponse) ProtoMessage()    {}
func (*CopyLocalToRemoteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b70380debb315ef, []int{2}
}

func (m *CopyLocalToRemoteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CopyLocalToRemoteResponse.Unmarshal(m, b)
}
func (m *CopyLocalToRemoteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CopyLocalToRemoteResponse.Marshal(b, m, deterministic)
}
func (m *CopyLocalToRemoteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CopyLocalToRemoteResponse.Merge(m, src)
}
func (m *CopyLocalToRemoteResponse) XXX_Size() int {
	return xxx_messageInfo_CopyLocalToRemoteResponse.Size(m)
}
func (m *CopyLocalToRemoteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CopyLocalToRemoteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CopyLocalToRemoteResponse proto.InternalMessageInfo

func (m *CopyLocalToRemoteResponse) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

func init() {
	proto.RegisterType((*Sftp)(nil), "sftp.Sftp")
	proto.RegisterType((*CopyLocalToRemoteRequest)(nil), "sftp.CopyLocalToRemoteRequest")
	proto.RegisterType((*CopyLocalToRemoteResponse)(nil), "sftp.CopyLocalToRemoteResponse")
}

func init() { proto.RegisterFile("SftpPb/sftp.proto", fileDescriptor_1b70380debb315ef) }

var fileDescriptor_1b70380debb315ef = []byte{
	// 248 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x90, 0x41, 0x4b, 0xc3, 0x40,
	0x10, 0x85, 0x89, 0xc6, 0x58, 0xc7, 0x93, 0x7b, 0x90, 0xb5, 0x87, 0x2a, 0x3d, 0x79, 0xaa, 0xd0,
	0xde, 0x3c, 0x2a, 0x08, 0xa2, 0x48, 0x49, 0x0a, 0x82, 0x9e, 0x92, 0x74, 0x82, 0x85, 0xa4, 0xb3,
	0xee, 0x6c, 0x84, 0xfc, 0x0b, 0x7f, 0xb2, 0xcc, 0x6e, 0xd7, 0x53, 0x7b, 0xcb, 0xc7, 0x97, 0xe1,
	0xbd, 0xb7, 0x70, 0x51, 0x34, 0xce, 0x2c, 0xab, 0x3b, 0x6e, 0x9c, 0x99, 0x19, 0x4b, 0x8e, 0x54,
	0x2a, 0xdf, 0xd3, 0xdf, 0x04, 0x52, 0x71, 0x6a, 0x0c, 0xa3, 0x9e, 0xd1, 0x6e, 0xcb, 0x0e, 0x75,
	0x72, 0x93, 0xdc, 0x9e, 0xe5, 0xff, 0x2c, 0xce, 0x94, 0xcc, 0xef, 0x64, 0xd7, 0xfa, 0x28, 0xb8,
	0xc8, 0xe2, 0x78, 0x60, 0x87, 0xdd, 0xf3, 0x5a, 0x1f, 0x07, 0x17, 0x59, 0x69, 0x38, 0xfd, 0x22,
	0x76, 0x2f, 0x38, 0xe8, 0xd4, 0xab, 0x88, 0x72, 0xd5, 0x6c, 0x5a, 0x7c, 0x93, 0xb4, 0x93, 0x70,
	0x15, 0x79, 0x7a, 0x0f, 0xfa, 0x91, 0xcc, 0xf0, 0x4a, 0x75, 0xd9, 0xae, 0x28, 0xc7, 0x8e, 0x1c,
	0xe6, 0xf8, 0xdd, 0x23, 0x3b, 0x35, 0x01, 0x5f, 0xdb, 0x37, 0x3c, 0x9f, 0xc3, 0xcc, 0xef, 0x91,
	0xfe, 0x79, 0x98, 0xb3, 0x80, 0xab, 0x3d, 0xb7, 0x6c, 0x68, 0xcb, 0xa8, 0x2e, 0x21, 0xb3, 0xc8,
	0x7d, 0xeb, 0x76, 0x03, 0x77, 0x34, 0xaf, 0x21, 0x2d, 0x9e, 0x56, 0x4b, 0xf5, 0xb9, 0x27, 0xb8,
	0x40, 0xfb, 0xb3, 0xa9, 0x51, 0x4d, 0x42, 0xd4, 0xa1, 0x62, 0xe3, 0xeb, 0x83, 0x3e, 0x84, 0x3f,
	0x8c, 0x3e, 0x32, 0xf9, 0xc3, 0x54, 0x55, 0xe6, 0xdf, 0x7f, 0xf1, 0x17, 0x00, 0x00, 0xff, 0xff,
	0x50, 0xee, 0xfe, 0xec, 0x94, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SFTPClient is the client API for SFTP service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SFTPClient interface {
	CopyLocalToRemoteService(ctx context.Context, in *CopyLocalToRemoteRequest, opts ...grpc.CallOption) (*CopyLocalToRemoteResponse, error)
}

type sFTPClient struct {
	cc *grpc.ClientConn
}

func NewSFTPClient(cc *grpc.ClientConn) SFTPClient {
	return &sFTPClient{cc}
}

func (c *sFTPClient) CopyLocalToRemoteService(ctx context.Context, in *CopyLocalToRemoteRequest, opts ...grpc.CallOption) (*CopyLocalToRemoteResponse, error) {
	out := new(CopyLocalToRemoteResponse)
	err := c.cc.Invoke(ctx, "/sftp.SFTP/CopyLocalToRemoteService", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SFTPServer is the server API for SFTP service.
type SFTPServer interface {
	CopyLocalToRemoteService(context.Context, *CopyLocalToRemoteRequest) (*CopyLocalToRemoteResponse, error)
}

// UnimplementedSFTPServer can be embedded to have forward compatible implementations.
type UnimplementedSFTPServer struct {
}

func (*UnimplementedSFTPServer) CopyLocalToRemoteService(ctx context.Context, req *CopyLocalToRemoteRequest) (*CopyLocalToRemoteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CopyLocalToRemoteService not implemented")
}

func RegisterSFTPServer(s *grpc.Server, srv SFTPServer) {
	s.RegisterService(&_SFTP_serviceDesc, srv)
}

func _SFTP_CopyLocalToRemoteService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CopyLocalToRemoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SFTPServer).CopyLocalToRemoteService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sftp.SFTP/CopyLocalToRemoteService",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SFTPServer).CopyLocalToRemoteService(ctx, req.(*CopyLocalToRemoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _SFTP_serviceDesc = grpc.ServiceDesc{
	ServiceName: "sftp.SFTP",
	HandlerType: (*SFTPServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CopyLocalToRemoteService",
			Handler:    _SFTP_CopyLocalToRemoteService_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "SftpPb/sftp.proto",
}
